### ISSUE TITLE
Пункт <не задано> во всех полях.

### ISSUE THREAD

**Issue by dxon** [vitalii-nechaev/DocGOST#1]
Добрый день. Проект создан в Altium Designer 21.2.0, при импорте в DocGOST нет возможности выбрать чего-либо в окне "Параметры импорта". Просто пункт <не задано> во всех полях, при раскрытии списка также только этот пункт.
![2021-04-20_11-37-29](https://user-images.githubusercontent.com/5267030/115338371-e4441700-a1cc-11eb-914a-28d16791e1f8.png)

**Comment by dxon** [comment]
И кстати, поддерживает ли программа варианты/исполнения при создании документации??

**Comment by dxon** [comment]
Попробовал пересохранить проект примера в AD21 - DocGOST  тоже перестает видеть поля свойств компонентов при импорте. Видимо, что-то изменили в формате *.Sch.

**Comment by vitalii-nechaev** [comment]
> Попробовал пересохранить проект примера в AD21 - DocGOST тоже перестает видеть поля свойств компонентов при импорте. Видимо, что-то изменили в формате *.Sch.

Действительно, была проблема при импорте данных из разных версий AD, связанная с различиями в строчных/заглавных буквах в названиях свойств. В последнем релизе DocGOST эта проблема устранена путём преобразования всех названий свойств в строки только с заглавными буквами.

**Comment by vitalii-nechaev** [comment]
> И кстати, поддерживает ли программа варианты/исполнения при создании документации??

Варианты /исполнения в DocGOST пока не поддерживаются.
